Docs reorganization
yearn/yearn-docs pull request #233
Opened 2021-04-26 18:47 UTC by philburrrt

Restructured docs layouts. New copy only where necessary and some obviously needed updates were fixed.

visual here: 
https://philbertburrow.gitbook.io/yearn-docs/v/docs-reorganization/

2021-04-27 09:24 UTC, lehnberg approved these changes
Awesome work, this looks good to me. Will ask for a couple of more 👀 on it before we merge.

2021-04-27 10:06 UTC, milkyklim commented on README.md
> +Discord [http://discord.yearn.finance](https://discord.gg/BUAFD9DUe)
Keep this link as http://discord.yearn.finance it will be resolved to proper invite on domain manager.

2021-04-27 10:10 UTC, milkyklim commented on SUMMARY.md
> +  - [implementation](governance/governance-process/implementation.md)
**I**mplementation

2021-04-27 10:11 UTC, milkyklim commented on governance/governance-process/README.md
> +The Yearn ecosystem is controlled by YFI token holders who submit and vote on off-chain proposals that govern the ecosystem. Proposals that generate a majority support (>50% of the vote) are implemen
> Please refer to our FAQ

Can we add a link to FAQ here?

2021-04-27 10:11 UTC, milkyklim commented on governance/governance-process/discussion.md
> + - [Discord](https://discord.gg/BUAFD9DU)
http://discord.yearn.finance

2021-04-27 10:17 UTC, milkyklim commented on governance/governance-process/implementation.md
> +Once a Snapshot vote has received over 50% support after 5 days of voting, changes will be implemented by Yearn's protocol or operations team and signed by the multi-sig, if necessary.
Better replace with *majority* cause it's possible people push multi option vote.

2021-04-27 10:18 UTC, milkyklim commented on governance/governance-process/voting.md
> +- Holding or staking YFI in the following places will enable you to vote on Yearn's [Snapshot](https://snapshot.page/#/yearn) page:
+ Bancor

2021-04-27 10:19 UTC, milkyklim commented on governance/governance-process/voting.md
> +	- Your wallet
This is not correct, you waller doesn't work

2021-04-27 10:22 UTC, milkyklim commented on governance/governance-process/voting.md
> +- Holding or staking YFI in the following places will enable you to vote on Yearn's [Snapshot](https://snapshot.page/#/yearn) page:
Here is the exact list: https://github.com/banteg/guest-list/pull/10#issue-599647475

2021-04-27 15:35 UTC, listonjesse commented on README.md
> +Discord [http://discord.yearn.finance](https://discord.gg/BUAFD9DUe)
Yes, I changed this with my earlier PR, but now the link is fixed by @nymmrx so let's revert back to it

2021-04-27 16:48 UTC, DarkGhost7 requested changes

2021-04-27 16:48 UTC, DarkGhost7 commented on README.md
>  Yearn Finance is a suite of products in Decentralized Finance (DeFi) that provides lending aggregation, yield generation, and insurance on the Ethereum blockchain. The protocol is maintained by vario
```suggestion
Yearn Finance is a suite of products in Decentralized Finance (DeFi) that provides lending aggregation and yield generation on the Ethereum blockchain. The protocol is maintained by various independent developers and is governed by YFI holders.
```
Do we still provide insurance?

2021-04-27 17:19 UTC, DarkGhost7 requested changes

2021-04-27 17:19 UTC, DarkGhost7 commented on resources/links.md
> +### Vaults Detail Reference
```suggestion
### Vault Strategies

* [Vaults at Yearn](https://medium.com/yearn-state-of-the-vaults/the-vaults-at-yearn-9237905ffed3)
* [yVaults v2 Strategies](https://yearn-hub.vercel.app/)

### Statistics

* [Yearn Dashboard](https://yearn.vision)
* [Yearn TVL](https://yearn.science/)
* [Initial Distribution Dashboard](https://explore.duneanalytics.com/dashboard/yearn)
* [Voting Stats Dashboard](https://explore.duneanalytics.com/public/dashboards/Lqnxzm7fa8NVhKC4kc37DDFPZgqXryaIjyLRYAYp)
* [Vaults Stats Dashboard](https://explore.duneanalytics.com/public/dashboards/g0bGfgloeXBd9C18jpBjdXi5KkQjR7IXYqFRUnHk)
* [Yearn API](https://vaults.finance/all)

```

2021-04-27 17:19 UTC, DarkGhost7 commented on resources/links.md
> +### Vaults Detail Reference
Deleted outdated links and added newer ones that are maintained actively.

2021-04-27 17:21 UTC, DarkGhost7 commented on resources/links.md
> +### Vaults Detail Reference
if it's not clear all this should be deleted
### Vaults Detail Reference

* [https://vaults.finance/](https://vaults.finance/)

* [yieldfarming.info](https://yieldfarming.info/)
* [stats.finance/yearn](https://stats.finance/yearn)
* [Feel The Yearn](https://feel-the-yearn.vercel.app/)

2021-04-27 17:50 UTC, philburrrt commented on resources/links.md
> +### Vaults Detail Reference
Thanks, fixed it.

2021-05-04 13:11 UTC, milkyklim approved these changes

2021-05-13 21:54 UTC, closed without merging