[DOC-72] feat: expand FAQ
yearn/yearn-docs pull request #447
Opened 2021-06-29 00:45 UTC by philburrrt

2021-06-29 08:06 UTC, lehnberg commented on resources/faq.md
> +#### I'm having issues with yearn.fi
I'd suggest we reconsider this answer from a couple of angles:

- There is no `official` when it comes to Yearn, so doesn't make sense to have an 'officially supported UI' either. 
- I wouldn't talk about interfaces having unique problems, sounds like we're FUDing other websites. 
- "Yearn's co-founder" refers to Andre, Yearn's sole founder?
- "Use at your own risk" goes for using the yearn.finance website as well. 

An alternative answer might be:

```
#### I'm having issues with yearn.fi

This website is one of many front-ends maintained by separate groups of developers. Consider getting in touch with the yearn.fi development team via their website or through social media channels.
```

2021-06-29 08:06 UTC, lehnberg requested changes
@philburrrt nice work, see one comment about yearn.fi

2021-07-06 22:29 UTC, philburrrt commented on resources/faq.md
> +#### I'm having issues with yearn.fi
Sounds a lot better. Thanks for clarifying. Was going off of how the relentless yearn.fi questions were responded to in Discord.

2021-07-27 08:21 UTC, lehnberg approved these changes

2021-07-27 08:21 UTC, merged