Hindi proof read for Proposal Process
yearn/yearn-docs pull request #491
Opened 2021-07-24 07:35 UTC by Major-Rager

2021-07-26 21:49 UTC, philburrrt requested changes

2021-07-26 21:49 UTC, philburrrt commented on governance/proposal-process.md
> -	- Sushiswap YFI/WETH LP टोकन मास्टरशेफ में दांव पर लगा
Since this is a brand, we need to keep it in English, otherwise people won't be able to find the site.

2021-07-27 02:35 UTC, Major-Rager commented on governance/proposal-process.md
Most of the protocol and brand names have been changed as requested.

2021-07-27 20:19 UTC, philburrrt commented on governance/proposal-process.md
Thank you!!

2021-07-27 20:19 UTC, merged