Add using yearn  - japanese [INT2-110]
yearn/yearn-docs pull request #580
Opened 2021-08-17 10:11 UTC by CRIPU

thanks!

2021-09-23 11:44 UTC, DarkGhost7 requested changes

2021-09-23 11:44 UTC, DarkGhost7 commented on using-yearn.md
> +# yearnの使い方
> yearnの使い方
change to `Yearnの使い方`

2021-09-23 11:44 UTC, DarkGhost7 commented on using-yearn.md
> +
delete line 13 extra space

2021-09-23 11:44 UTC, DarkGhost7 commented on using-yearn.md
> +
delete extra space at line 28

2021-09-23 11:44 UTC, DarkGhost7 commented on using-yearn.md
> +
delete extra space at line 56

2021-09-23 11:44 UTC, DarkGhost7 commented on using-yearn.md
> +
extra space line 100

2021-09-23 11:44 UTC, DarkGhost7 commented on using-yearn.md
> +
extra space 107

2021-09-23 13:00 UTC, CRIPU commented
fixed it ! thank you so much

2021-10-05 11:10 UTC, DarkGhost7 approved these changes
lgtm

2021-10-05 11:10 UTC, merged