Add yfi [INT2-113]
yearn/yearn-docs pull request #585
Opened 2021-09-12 03:04 UTC by CRIPU

about yfi thanks!

2021-10-04 14:35 UTC, DarkGhost7 requested changes

2021-10-04 14:35 UTC, DarkGhost7 commented on governance/yfi.md
> +
at line 16 should be this, was it translated?
```From the week of YFI's emergence, there was extensive discussion around emissions, supply and powers of token holders.```

2021-10-04 14:35 UTC, DarkGhost7 commented on governance/yfi.md
> +[YIP-61](https://snapshot.org/#/ybaby.eth/proposal/QmSMyYeKrRpnA7Xn56o2NtbCUzxmhzCupL7LxMA1reXxq4)に記載されているガバナンス 2.0 では、YFIトークン保有者の責任が、Yearn Improvement Proposals（YIPs）の作成と投票から、Yearn Delegation Propos
```Yearn Improvement Proposals（YIPs）の作成と投票から、Yearn Delegation Proposals（YDPs）および Yearn Signaling Proposals```
Translate 
Improvement proposal, delegation proposals, signaling proposals

2021-10-05 06:20 UTC, CRIPU commented on governance/yfi.md
> +
From the week of YFI's emergence, there was extensive discussion around emissions, supply and powers of token holders.
=
「YFIが台頭した週から、排出量、供給量、トークン保有者の権限をめぐって広範な議論が行われました。」 at line 14!

2021-10-05 06:50 UTC, CRIPU commented on governance/yfi.md
> +[YIP-61](https://snapshot.org/#/ybaby.eth/proposal/QmSMyYeKrRpnA7Xn56o2NtbCUzxmhzCupL7LxMA1reXxq4)に記載されているガバナンス 2.0 では、YFIトークン保有者の責任が、Yearn Improvement Proposals（YIPs）の作成と投票から、Yearn Delegation Propos
Yearn改善プロポーザル（YIPs）の作成と投票から、Yearnデリゲーションプロポーザル（YDPs）およびYearnシグナリングプロポーザル（YSPs）
I translated!
I search about Delegation and Signaling, in Japan, they are written in katakana as a business term

2021-10-05 10:59 UTC, merged