Add governance and operations [INT2-114]
yearn/yearn-docs pull request #586
Opened 2021-09-13 10:25 UTC by CRIPU

done :) thanks!

2021-10-04 14:22 UTC, DarkGhost7 requested changes

2021-10-04 14:22 UTC, DarkGhost7 commented on governance/governance-and-operations.md
> +2021年4月25日に[YIP-61: Governance 2.0](https://gov.yearn.finance/t/yip-61-governance-2-0/10460)が可決されて以来、Yearnは**制約付委譲**によって管理される**マルチDAO**構造への移行を開始しました。このアプローチにより、プロトコル開発が官僚制度によって硬直化することなく、十分なレベルの分権性を維持
```YIP-61: Governance 2.0```
Translate Governance

2021-10-04 14:22 UTC, DarkGhost7 commented on governance/governance-and-operations.md
> +|yBrain|戦略の管理|戦略の有効化、無効化、調整、維持をします。|
same as the ones below if possible

2021-10-05 08:09 UTC, CRIPU commented on governance/governance-and-operations.md
> +2021年4月25日に[YIP-61: Governance 2.0](https://gov.yearn.finance/t/yip-61-governance-2-0/10460)が可決されて以来、Yearnは**制約付委譲**によって管理される**マルチDAO**構造への移行を開始しました。このアプローチにより、プロトコル開発が官僚制度によって硬直化することなく、十分なレベルの分権性を維持
ガバナンス
I fixed it! thank u !

2021-10-05 08:09 UTC, CRIPU commented on governance/governance-and-operations.md
> +    1. YFIホルダーがyTeamの作成、破壊、制限を定義する
I fixed it sorry > <

2021-10-05 08:10 UTC, CRIPU commented on governance/governance-and-operations.md
> +    3. yTx が委任されたトランザクションを作成し、それをマルチシグに送信する
I translated it as トランザクション
thanks!

2021-10-05 08:10 UTC, CRIPU commented on governance/governance-and-operations.md
> +|Yearn Improvement Proposal (YIP)|YFIホルダーに委任された権限、または議会の権限の範囲外の権限を実行する提案|
I translated it as 改善プロポーザル thanks!

2021-10-05 08:10 UTC, CRIPU commented on governance/governance-and-operations.md
> +|yOps署名者の変更|yOpsが他のyチームの署名者を変更する力を持っているように、これはyOpsの署名者を変更する特別な力です。|
I translated it as オペレーション
Thanks!

2021-10-05 08:11 UTC, CRIPU commented on governance/governance-and-operations.md
> +|yGuard|vaultsを守る｜YFI Protocol Dev, YFI Strategists, YFI Mechanics, YFI Secret Admirers|
I think it's better to keep that part in English.
how do you think?

2021-10-05 08:11 UTC, CRIPU commented on governance/governance-and-operations.md
> +|yBrain|戦略の管理|戦略の有効化、無効化、調整、維持をします。|
I fixed these part as katakana
thanks!

2021-10-05 10:55 UTC, merged