Add proposalprosess
yearn/yearn-docs pull request #588
Opened 2021-09-21 05:20 UTC by CRIPU

2021-10-04 14:03 UTC, DarkGhost7 requested changes
Translate more, but looks good other than that!

2021-10-04 14:03 UTC, DarkGhost7 commented on governance/proposal-process.md
> +	- Balancer YFI/WETH LP token
```
	- Balancer YFI/WETH LP token
```
maybe translate token?

2021-10-04 14:03 UTC, DarkGhost7 commented on governance/proposal-process.md
> +	- Sushiswap YFI/WETH LP token staked in MasterChef
```
token staked in
```
Maybe translate?

2021-10-04 14:03 UTC, DarkGhost7 commented on governance/proposal-process.md
> +	- Unit Protocol YFI collateral
```collateral```
maybe translate

2021-10-05 06:14 UTC, CRIPU commented on governance/proposal-process.md
> +	- Balancer YFI/WETH LP token
BalancerのYFI/WETH LPトークン
I fixed it thank you

2021-10-05 06:14 UTC, CRIPU commented on governance/proposal-process.md
> +	- Sushiswap YFI/WETH LP token staked in MasterChef
I fixed it sorry > <

2021-10-05 06:15 UTC, CRIPU commented on governance/proposal-process.md
> +	- Unit Protocol YFI collateral
担保、I fixed it thanks!

2021-10-05 10:28 UTC, closed without merging